//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_ProjectWeb_Mohamad_Nour.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class registration
    {
        public int id { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string identification_number { get; set; }
        public Nullable<int> job_id { get; set; }
        public Nullable<int> group_id { get; set; }
        public Nullable<int> mobile_number { get; set; }
        public string email_ad { get; set; }
    
        public virtual group group { get; set; }
        public virtual job job { get; set; }
    }
}
